# 若lib/quick_algo目录下有文件被修改，则运行pytest
name: QuickAlgo CI
on:
  workflow_dispatch:
  push:
    paths:
      - 'lib/quick_algo/**'
  pull_request:
    paths:
      - 'lib/quick_algo/**'

jobs:
  build-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-14, macos-13]
        python-version: ["3.12"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install build tools (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential
      - name: Ensure MSVC Build Tools (Windows)
        if: runner.os == 'Windows'
        run: |
          echo "MSVC tools will be automatically available on windows-latest"
      - name: Install dependencies
        run: |
          pip install cython build setuptools py-cpuinfo wheel pytest numpy scipy networkx

      - name: Build and install
        working-directory: lib/quick_algo
        run: python ./build_lib.py --cleanup --cythonize --install

      - name: Run tests and generate report
        working-directory: lib/quick_algo
        run: pytest ./tests